# install python via miniconda
ENV PATH=/work/opt/venv/bin:$$PATH
ENV UV_PYTHON_INSTALL_DIR=/work/opt/python
ENV RUSTUP_HOME=/work/opt/rustup
ENV CARGO_HOME=/work/opt/cargo

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked,mode=0755 \
    --mount=target=/var/cache/apt,type=cache,sharing=locked,mode=0755 \
    set -eux; \
    apt update; \
    apt install -y --no-install-recommends \
    pkg-config \
    libssl-dev \
    ; \
    rm -rf /var/lib/apt/lists/*

# install fnm/node
RUN --mount=target=/root/.cache/pip,type=cache,sharing=locked,mode=0755 \
    set -eux; \
    if [ "$$TARGETARCH" = "arm64" ]; then \
    ARCH="aarch64"; \
    else \
    ARCH="x86_64"; \
    fi; \
    curl -o /tmp/rustup.sh -sSf https://sh.rustup.rs; \
    sh /tmp/rustup.sh -y --no-modify-path; \
    rm -fr /work/opt/rustup/toolchains/stable-$${ARCH}-unknown-linux-gnu/share/doc;

# install sccache
RUN set -eux; \
    if [ "$$TARGETARCH" = "arm64" ]; then \
    ARCH="aarch64"; \
    else \
    ARCH="x86_64"; \
    fi; \
    curl -o /tmp/sccache.tgz -LsSf --retry 5 --retry-all-errors --retry-delay 2 https://github.com/mozilla/sccache/releases/download/v$SCCACHE_VERSION/sccache-v$SCCACHE_VERSION-$${ARCH}-unknown-linux-musl.tar.gz; \
    tar -C /work/opt/bin --strip-components=1 -xf /tmp/sccache.tgz sccache-v$SCCACHE_VERSION-$${ARCH}-unknown-linux-musl/sccache; \
    chmod +x /work/opt/bin/sccache; \
    rm /tmp/sccache.tgz
