FROM postgis/postgis:17-3.6-alpine AS builder

RUN set -x; \
    apk update \
    && apk add \
    git \
    build-base \
    clang19 \
    llvm19-dev

ENV LLVM_CONFIG=/usr/bin/llvm-config-19

RUN set -x; \
    cd /tmp \
    && find / | grep postgresql | grep -v "/tmp" > /tmp/pg_paths_before.txt \
    && git clone --depth 1 --branch v0.8.1 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && find / | grep postgresql | grep -v "/tmp" > /tmp/pg_paths_after.txt

FROM postgis/postgis:17-3.6-alpine AS final

COPY --from=builder /usr/local/lib/postgresql/bitcode/vector.index.bc /usr/local/lib/postgresql/bitcode/vector.index.bc
COPY --from=builder /usr/local/lib/postgresql/bitcode/vector /usr/local/lib/postgresql/bitcode/vector
COPY --from=builder /usr/local/lib/postgresql/vector.so /usr/local/lib/postgresql/vector.so
COPY --from=builder /usr/local/share/postgresql/extension/vector* /usr/local/share/postgresql/extension/
COPY --from=builder /usr/local/include/postgresql/server/extension/vector /usr/local/include/postgresql/server/extension/vector

LABEL org.opencontainers.image.postgis_version="17-3.6-alpine"
LABEL org.opencontainers.image.pgvector_version="0.8.1"
