# SBOM for rust

## base image digest

ghcr.io/linuxserver/baseimage-debian@sha256:aa7315e2a457a69babaacda5c83fc6a6f88e895ab6d236e5b070ba41beb6b71a

## Package Versions

build_version=Linuxserver.io version:- 85a6aea0-ls48 Build-date:- 2025-01-19T10:51:29+00:00
org.opencontainers.image.dockerize_version=0.7.0
org.opencontainers.image.rust_version=1.84.0
org.opencontainers.image.watchexec_version=2.1.2

## OS Versions

[migrations] started
[migrations] no migrations found
    :::::::::  :::    :::  :::::::: ::::::::::: 
    :+:    :+: :+:    :+: :+:    :+:    :+:     
    +:+    +:+ +:+    +:+ +:+           +:+     
    +#++:++#:  +#+    +:+ +#++:++#++    +#+     
    +#+    +#+ +#+    +#+        +#+    +#+     
    #+#    #+# #+#    #+# #+#    #+#    #+#     
    ###    ###  ########   ########     ###   

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version                        Architecture Description
+++-=========================-==============================-============-===============================================================================
ii  adduser                   3.134                          all          add and remove users and groups
ii  apt                       2.6.1                          amd64        commandline package manager
ii  apt-utils                 2.6.1                          amd64        package management related utility programs
ii  base-files                12.4+deb12u9                   amd64        Debian base system miscellaneous files
ii  base-passwd               3.6.1                          amd64        Debian base system master password and group files
ii  bash                      5.2.15-2+b7                    amd64        GNU Bourne Again SHell
ii  binutils                  2.40-2                         amd64        GNU assembler, linker and binary utilities
ii  binutils-common:amd64     2.40-2                         amd64        Common files for the GNU assembler, linker and binary utilities
ii  binutils-x86-64-linux-gnu 2.40-2                         amd64        GNU binary utilities, for x86-64-linux-gnu target
ii  bsd-mailx                 8.1.2-0.20220412cvs-1          amd64        simple mail user agent
ii  bsdutils                  1:2.38.1-5+deb12u3             amd64        basic utilities from 4.4BSD-Lite
ii  build-essential           12.9                           amd64        Informational list of build-essential packages
ii  bzip2                     1.0.8-5+b1                     amd64        high-quality block-sorting file compressor - utilities
ii  ca-certificates           20230311                       all          Common CA certificates
ii  catatonit                 0.1.7-1+b1                     amd64        init process for containers
ii  coreutils                 9.1-1                          amd64        GNU core utilities
ii  cpp                       4:12.2.0-3                     amd64        GNU C preprocessor (cpp)
ii  cpp-12                    12.2.0-14                      amd64        GNU C preprocessor
ii  cron                      3.0pl1-162                     amd64        process scheduling daemon
ii  cron-daemon-common        3.0pl1-162                     all          process scheduling daemon's configuration files
ii  curl                      7.88.1-10+deb12u8              amd64        command line tool for transferring data with URL syntax
ii  dash                      0.5.12-2                       amd64        POSIX-compliant shell
ii  debconf                   1.5.82                         all          Debian configuration management system
ii  debian-archive-keyring    2023.3+deb12u1                 all          GnuPG archive keys of the Debian archive
ii  debianutils               5.7-0.5~deb12u1                amd64        Miscellaneous utilities specific to Debian
ii  diffutils                 1:3.8-4                        amd64        File comparison utilities
ii  dirmngr                   2.2.40-1.1                     amd64        GNU privacy guard - network certificate management service
ii  dpkg                      1.21.22                        amd64        Debian package management system
ii  dpkg-dev                  1.21.22                        all          Debian package development tools
ii  e2fsprogs                 1.47.0-2                       amd64        ext2/ext3/ext4 file system utilities
ii  exim4-base                4.96-15+deb12u6                amd64        support files for all Exim MTA (v4) packages
ii  exim4-config              4.96-15+deb12u6                all          configuration for the Exim MTA (v4)
ii  exim4-daemon-light        4.96-15+deb12u6                amd64        lightweight Exim MTA (v4) daemon
ii  file                      1:5.44-3                       amd64        Recognize the type of data in a file using "magic" numbers
ii  findutils                 4.9.0-4                        amd64        utilities for finding files--find, xargs
ii  g++                       4:12.2.0-3                     amd64        GNU C++ compiler
ii  g++-12                    12.2.0-14                      amd64        GNU C++ compiler
ii  gcc                       4:12.2.0-3                     amd64        GNU C compiler
ii  gcc-12                    12.2.0-14                      amd64        GNU C compiler
ii  gcc-12-base:amd64         12.2.0-14                      amd64        GCC, the GNU Compiler Collection (base package)
ii  git                       1:2.39.5-0+deb12u1             amd64        fast, scalable, distributed revision control system
ii  git-lfs                   3.3.0-1+b5                     amd64        Git Large File Support
ii  git-man                   1:2.39.5-0+deb12u1             all          fast, scalable, distributed revision control system (manual pages)
ii  gnupg                     2.2.40-1.1                     all          GNU privacy guard - a free PGP replacement
ii  gnupg-l10n                2.2.40-1.1                     all          GNU privacy guard - localization files
ii  gnupg-utils               2.2.40-1.1                     amd64        GNU privacy guard - utility programs
ii  gpg                       2.2.40-1.1                     amd64        GNU Privacy Guard -- minimalist public key operations
ii  gpg-agent                 2.2.40-1.1                     amd64        GNU privacy guard - cryptographic agent
ii  gpg-wks-client            2.2.40-1.1                     amd64        GNU privacy guard - Web Key Service client
ii  gpg-wks-server            2.2.40-1.1                     amd64        GNU privacy guard - Web Key Service server
ii  gpgconf                   2.2.40-1.1                     amd64        GNU privacy guard - core configuration utilities
ii  gpgsm                     2.2.40-1.1                     amd64        GNU privacy guard - S/MIME version
ii  gpgv                      2.2.40-1.1                     amd64        GNU privacy guard - signature verification tool
ii  grep                      3.8-5                          amd64        GNU grep, egrep and fgrep
ii  gzip                      1.12-1                         amd64        GNU compression utilities
ii  hostname                  3.23+nmu1                      amd64        utility to set/show the host name or domain name
ii  init-system-helpers       1.65.2                         all          helper tools for all init systems
ii  iproute2                  6.1.0-3                        amd64        networking and traffic control tools
ii  iputils-ping              3:20221126-1+deb12u1           amd64        Tools to test the reachability of network hosts
ii  jq                        1.6-2.1                        amd64        lightweight and flexible command-line JSON processor
ii  krb5-locales              1.20.1-2+deb12u2               all          internationalization support for MIT Kerberos
ii  libacl1:amd64             2.3.1-3                        amd64        access control list - shared library
ii  libapt-pkg6.0:amd64       2.6.1                          amd64        package management runtime library
ii  libasan8:amd64            12.2.0-14                      amd64        AddressSanitizer -- a fast memory error detector
ii  libassuan0:amd64          2.5.5-5                        amd64        IPC library for the GnuPG components
ii  libatomic1:amd64          12.2.0-14                      amd64        support library providing __atomic built-in functions
ii  libattr1:amd64            1:2.5.1-4                      amd64        extended attribute handling - shared library
ii  libaudit-common           1:3.0.9-1                      all          Dynamic library for security auditing - common files
ii  libaudit1:amd64           1:3.0.9-1                      amd64        Dynamic library for security auditing
ii  libbinutils:amd64         2.40-2                         amd64        GNU binary utilities (private shared library)
ii  libblkid1:amd64           2.38.1-5+deb12u3               amd64        block device ID library
ii  libbpf1:amd64             1:1.1.0-1                      amd64        eBPF helper library (shared library)
ii  libbrotli1:amd64          1.0.9-2+b6                     amd64        library implementing brotli encoder and decoder (shared libraries)
ii  libbsd0:amd64             0.11.7-2                       amd64        utility functions from BSD systems - shared library
ii  libbz2-1.0:amd64          1.0.8-5+b1                     amd64        high-quality block-sorting file compressor library - runtime
ii  libc-bin                  2.36-9+deb12u9                 amd64        GNU C Library: Binaries
ii  libc-dev-bin              2.36-9+deb12u9                 amd64        GNU C Library: Development binaries
ii  libc-l10n                 2.36-9+deb12u9                 all          GNU C Library: localization files
ii  libc6:amd64               2.36-9+deb12u9                 amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64           2.36-9+deb12u9                 amd64        GNU C Library: Development Libraries and Header Files
ii  libcap-ng0:amd64          0.8.3-1+b3                     amd64        alternate POSIX capabilities library
ii  libcap2:amd64             1:2.66-4                       amd64        POSIX 1003.1e capabilities (library)
ii  libcap2-bin               1:2.66-4                       amd64        POSIX 1003.1e capabilities (utilities)
ii  libcc1-0:amd64            12.2.0-14                      amd64        GCC cc1 plugin for GDB
ii  libcom-err2:amd64         1.47.0-2                       amd64        common error description library
ii  libcrypt-dev:amd64        1:4.4.33-2                     amd64        libcrypt development files
ii  libcrypt1:amd64           1:4.4.33-2                     amd64        libcrypt shared library
ii  libctf-nobfd0:amd64       2.40-2                         amd64        Compact C Type Format library (runtime, no BFD dependency)
ii  libctf0:amd64             2.40-2                         amd64        Compact C Type Format library (runtime, BFD dependency)
ii  libcurl3-gnutls:amd64     7.88.1-10+deb12u8              amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4:amd64            7.88.1-10+deb12u8              amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libdb5.3:amd64            5.3.28+dfsg2-1                 amd64        Berkeley v5.3 Database Libraries [runtime]
ii  libdebconfclient0:amd64   0.270                          amd64        Debian Configuration Management System (C-implementation library)
ii  libdpkg-perl              1.21.22                        all          Dpkg perl modules
ii  libelf1:amd64             0.188-2.1                      amd64        library to read and write ELF files
ii  liberror-perl             0.17029-2                      all          Perl module for error/exception handling in an OO-ish way
ii  libevent-2.1-7:amd64      2.1.12-stable-8                amd64        Asynchronous event notification library
ii  libexpat1:amd64           2.5.0-1+deb12u1                amd64        XML parsing C library - runtime library
ii  libext2fs2:amd64          1.47.0-2                       amd64        ext2/ext3/ext4 file system libraries
ii  libffi8:amd64             3.4.4-1                        amd64        Foreign Function Interface library runtime
ii  libgcc-12-dev:amd64       12.2.0-14                      amd64        GCC support library (development files)
ii  libgcc-s1:amd64           12.2.0-14                      amd64        GCC support library
ii  libgcrypt20:amd64         1.10.1-3                       amd64        LGPL Crypto library - runtime library
ii  libgdbm-compat4:amd64     1.23-3                         amd64        GNU dbm database routines (legacy support runtime version) 
ii  libgdbm6:amd64            1.23-3                         amd64        GNU dbm database routines (runtime version) 
ii  libgmp10:amd64            2:6.2.1+dfsg1-1.1              amd64        Multiprecision arithmetic library
ii  libgnutls-dane0:amd64     3.7.9-2+deb12u3                amd64        GNU TLS library - DANE security support
ii  libgnutls30:amd64         3.7.9-2+deb12u3                amd64        GNU TLS library - main runtime library
ii  libgomp1:amd64            12.2.0-14                      amd64        GCC OpenMP (GOMP) support library
ii  libgpg-error0:amd64       1.46-1                         amd64        GnuPG development runtime library
ii  libgpm2:amd64             1.20.7-10+b1                   amd64        General Purpose Mouse - shared library
ii  libgprofng0:amd64         2.40-2                         amd64        GNU Next Generation profiler (runtime library)
ii  libgssapi-krb5-2:amd64    1.20.1-2+deb12u2               amd64        MIT Kerberos runtime libraries - krb5 GSS-API Mechanism
ii  libhogweed6:amd64         3.8.1-2                        amd64        low level cryptographic library (public-key cryptos)
ii  libicu72:amd64            72.1-3                         amd64        International Components for Unicode
ii  libidn12:amd64            1.41-1                         amd64        GNU Libidn library, implementation of IETF IDN specifications
ii  libidn2-0:amd64           2.3.3-1+b1                     amd64        Internationalized domain names (IDNA2008/TR46) library
ii  libisl23:amd64            0.25-1.1                       amd64        manipulating sets and relations of integer points bounded by linear constraints
ii  libitm1:amd64             12.2.0-14                      amd64        GNU Transactional Memory Library
ii  libjansson4:amd64         2.14-2                         amd64        C library for encoding, decoding and manipulating JSON data
ii  libjq1:amd64              1.6-2.1                        amd64        lightweight and flexible command-line JSON processor - shared library
ii  libk5crypto3:amd64        1.20.1-2+deb12u2               amd64        MIT Kerberos runtime libraries - Crypto Library
ii  libkeyutils1:amd64        1.6.3-2                        amd64        Linux Key Management Utilities (library)
ii  libkrb5-3:amd64           1.20.1-2+deb12u2               amd64        MIT Kerberos runtime libraries
ii  libkrb5support0:amd64     1.20.1-2+deb12u2               amd64        MIT Kerberos runtime libraries - Support library
ii  libksba8:amd64            1.6.3-2                        amd64        X.509 and CMS support library
ii  libldap-2.5-0:amd64       2.5.13+dfsg-5                  amd64        OpenLDAP libraries
ii  libldap-common            2.5.13+dfsg-5                  all          OpenLDAP common files for libraries
ii  liblockfile-bin           1.17-1+b1                      amd64        support binaries for and cli utilities based on liblockfile
ii  liblockfile1:amd64        1.17-1+b1                      amd64        NFS-safe locking library
ii  liblsan0:amd64            12.2.0-14                      amd64        LeakSanitizer -- a memory leak detector (runtime)
ii  liblz4-1:amd64            1.9.4-1                        amd64        Fast LZ compression algorithm library - runtime
ii  liblzma5:amd64            5.4.1-0.2                      amd64        XZ-format compression library
ii  libmagic-mgc              1:5.44-3                       amd64        File type determination library using "magic" numbers (compiled magic file)
ii  libmagic1:amd64           1:5.44-3                       amd64        Recognize the type of data in a file using "magic" numbers - library
ii  libmd0:amd64              1.0.4-2                        amd64        message digest functions from BSD systems - shared library
ii  libmnl0:amd64             1.0.4-3                        amd64        minimalistic Netlink communication library
ii  libmount1:amd64           2.38.1-5+deb12u3               amd64        device mounting library
ii  libmpc3:amd64             1.3.1-1                        amd64        multiple precision complex floating-point library
ii  libmpfr6:amd64            4.2.0-1                        amd64        multiple precision floating-point computation
ii  libncursesw6:amd64        6.4-4                          amd64        shared libraries for terminal handling (wide character support)
ii  libnettle8:amd64          3.8.1-2                        amd64        low level cryptographic library (symmetric and one-way cryptos)
ii  libnghttp2-14:amd64       1.52.0-1+deb12u2               amd64        library implementing HTTP/2 protocol (shared library)
ii  libnpth0:amd64            1.6-3                          amd64        replacement for GNU Pth using system threads
ii  libnsl-dev:amd64          1.3.0-2                        amd64        libnsl development files
ii  libnsl2:amd64             1.3.0-2                        amd64        Public client interface for NIS(YP) and NIS+
ii  libonig5:amd64            6.9.8-1                        amd64        regular expressions library
ii  libp11-kit0:amd64         0.24.1-2                       amd64        library for loading and coordinating access to PKCS#11 modules - runtime
ii  libpam-modules:amd64      1.5.2-6+deb12u1                amd64        Pluggable Authentication Modules for PAM
ii  libpam-modules-bin        1.5.2-6+deb12u1                amd64        Pluggable Authentication Modules for PAM - helper binaries
ii  libpam-runtime            1.5.2-6+deb12u1                all          Runtime support for the PAM library
ii  libpam0g:amd64            1.5.2-6+deb12u1                amd64        Pluggable Authentication Modules library
ii  libpcre2-8-0:amd64        10.42-1                        amd64        New Perl Compatible Regular Expression Library- 8 bit runtime files
ii  libperl5.36:amd64         5.36.0-7+deb12u1               amd64        shared Perl library
ii  libproc2-0:amd64          2:4.0.2-3                      amd64        library for accessing process information from /proc
ii  libpsl5:amd64             0.21.2-1                       amd64        Library for Public Suffix List (shared libraries)
ii  libquadmath0:amd64        12.2.0-14                      amd64        GCC Quad-Precision Math Library
ii  libreadline8:amd64        8.2-1.3                        amd64        GNU readline and history libraries, run-time libraries
ii  librtmp1:amd64            2.4+20151223.gitfa8646d.1-2+b2 amd64        toolkit for RTMP streams (shared library)
ii  libsasl2-2:amd64          2.1.28+dfsg-10                 amd64        Cyrus SASL - authentication abstraction library
ii  libsasl2-modules:amd64    2.1.28+dfsg-10                 amd64        Cyrus SASL - pluggable authentication modules
ii  libsasl2-modules-db:amd64 2.1.28+dfsg-10                 amd64        Cyrus SASL - pluggable authentication modules (DB)
ii  libseccomp2:amd64         2.5.4-1+deb12u1                amd64        high level interface to Linux seccomp filter
ii  libselinux1:amd64         3.4-1+b6                       amd64        SELinux runtime shared libraries
ii  libsemanage-common        3.4-1                          all          Common files for SELinux policy management libraries
ii  libsemanage2:amd64        3.4-1+b5                       amd64        SELinux policy management library
ii  libsepol2:amd64           3.4-2.1                        amd64        SELinux library for manipulating binary security policies
ii  libsmartcols1:amd64       2.38.1-5+deb12u3               amd64        smart column output alignment library
ii  libsodium23:amd64         1.0.18-1                       amd64        Network communication, cryptography and signaturing library
ii  libsqlite3-0:amd64        3.40.1-2+deb12u1               amd64        SQLite 3 shared library
ii  libss2:amd64              1.47.0-2                       amd64        command-line interface parsing library
ii  libssh2-1:amd64           1.10.0-3+b1                    amd64        SSH2 client-side library
ii  libssl3:amd64             3.0.15-1~deb12u1               amd64        Secure Sockets Layer toolkit - shared libraries
ii  libstdc++-12-dev:amd64    12.2.0-14                      amd64        GNU Standard C++ Library v3 (development files)
ii  libstdc++6:amd64          12.2.0-14                      amd64        GNU Standard C++ Library v3
ii  libsystemd0:amd64         252.33-1~deb12u1               amd64        systemd utility library
ii  libtasn1-6:amd64          4.19.0-2                       amd64        Manage ASN.1 structures (runtime)
ii  libtinfo6:amd64           6.4-4                          amd64        shared low-level terminfo library for terminal handling
ii  libtirpc-common           1.3.3+ds-1                     all          transport-independent RPC library - common files
ii  libtirpc-dev:amd64        1.3.3+ds-1                     amd64        transport-independent RPC library - development files
ii  libtirpc3:amd64           1.3.3+ds-1                     amd64        transport-independent RPC library
ii  libtsan2:amd64            12.2.0-14                      amd64        ThreadSanitizer -- a Valgrind-based detector of data races (runtime)
ii  libubsan1:amd64           12.2.0-14                      amd64        UBSan -- undefined behaviour sanitizer (runtime)
ii  libudev1:amd64            252.33-1~deb12u1               amd64        libudev shared library
ii  libunbound8:amd64         1.17.1-2+deb12u2               amd64        library implementing DNS resolution and validation
ii  libunistring2:amd64       1.0-2                          amd64        Unicode string library for C
ii  libuuid1:amd64            2.38.1-5+deb12u3               amd64        Universally Unique ID library
ii  libxtables12:amd64        1.8.9-2                        amd64        netfilter xtables library
ii  libxxhash0:amd64          0.8.1-1                        amd64        shared library for xxhash
ii  libzstd1:amd64            1.5.4+dfsg2-5                  amd64        fast lossless compression algorithm
ii  linux-libc-dev:amd64      6.1.124-1                      amd64        Linux support headers for userspace development
ii  locales                   2.36-9+deb12u9                 all          GNU C Library: National Language (locale) data [support]
ii  login                     1:4.13+dfsg1-1+b1              amd64        system login tools
ii  logsave                   1.47.0-2                       amd64        save the output of a command in a log file
ii  make                      4.3-4.1                        amd64        utility for directing compilation
ii  mawk                      1.3.4.20200120-3.1             amd64        Pattern scanning and text processing language
ii  mount                     2.38.1-5+deb12u3               amd64        tools for mounting and manipulating filesystems
ii  ncdu                      1.18-0.2                       amd64        ncurses disk usage viewer
ii  ncurses-base              6.4-4                          all          basic terminal type definitions
ii  ncurses-bin               6.4-4                          amd64        terminal-related programs and man pages
ii  netbase                   6.4                            all          Basic TCP/IP networking system
ii  netcat-traditional        1.10-47                        amd64        TCP/IP swiss army knife
ii  openssl                   3.0.15-1~deb12u1               amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  passwd                    1:4.13+dfsg1-1+b1              amd64        change and administer password and group data
ii  patch                     2.7.6-7                        amd64        Apply a diff file to an original
ii  perl                      5.36.0-7+deb12u1               amd64        Larry Wall's Practical Extraction and Report Language
ii  perl-base                 5.36.0-7+deb12u1               amd64        minimal Perl system
ii  perl-modules-5.36         5.36.0-7+deb12u1               all          Core Perl modules
ii  pinentry-curses           1.2.1-1                        amd64        curses-based PIN or pass-phrase entry dialog for GnuPG
ii  procps                    2:4.0.2-3                      amd64        /proc file system utilities
ii  psmisc                    23.6-1                         amd64        utilities that use the proc file system
ii  publicsuffix              20230209.2326-1                all          accurate, machine-readable list of domain name suffixes
ii  readline-common           8.2-1.3                        all          GNU readline and history libraries, common files
ii  rpcsvc-proto              1.4.3-1                        amd64        RPC protocol compiler and definitions
ii  sed                       4.9-1                          amd64        GNU stream editor for filtering/transforming text
ii  sensible-utils            0.0.17+nmu1                    all          Utilities for sensible alternative selection
ii  sysvinit-utils            3.06-4                         amd64        System-V-like utilities
ii  tar                       1.34+dfsg-1.2+deb12u1          amd64        GNU version of the tar archiving utility
ii  tzdata                    2024b-0+deb12u1                all          time zone and daylight-saving time data
ii  unzip                     6.0-28                         amd64        De-archiver for .zip files
ii  usr-is-merged             37~deb12u1                     all          Transitional package to assert a merged-/usr system
ii  util-linux                2.38.1-5+deb12u3               amd64        miscellaneous system utilities
ii  util-linux-extra          2.38.1-5+deb12u3               amd64        interactive login tools
ii  vim                       2:9.0.1378-2                   amd64        Vi IMproved - enhanced vi editor
ii  vim-common                2:9.0.1378-2                   all          Vi IMproved - Common files
ii  vim-runtime               2:9.0.1378-2                   all          Vi IMproved - Runtime files
ii  xz-utils                  5.4.1-0.2                      amd64        XZ-format compression utilities
ii  zlib1g:amd64              1:1.2.13.dfsg-1                amd64        compression library - runtime
