name: "Build Image"

inputs:
  service_name:
    description: "Service name. Example: python"
    required: true
  github_token:
    description: "GitHub token for creating/merging PR"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Log in to the Container registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup env
      run: cat config.env >> $GITHUB_ENV

    - name: Build Image
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: ./task ${{ inputs.service_name }}:build

    - name: Tag Python
      if: github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: ./task ${{ inputs.service_name }}:tag
