name: docker

services:
  caddy:
    profiles: ["all", "caddy"]
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy: http://caddy.fbi.com
      caddy.log: default
      caddy.log.level: INFO
    restart: unless-stopped

  py:
    profiles: ["all", "py"]
    image: ghcr.io/chris-garrett/python:latest
    command: |
      dockerize
        -wait tcp://o2:5080
        sh -c '
          # used these initial cmds to bootstrap the app. 
          # uv init --app --name pyapp .
          # uv add fastapi --extra standard

          uv sync 
          uv run fastapi dev --host 0.0.0.0
        '
    ports:
      - 8030:8000
    environment:
      - O2_TOKEN=ZG9ja2VyQGZiaS5jb206VTdGZmttQjFaY2dHb2FuOA==
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./py:/work/app
      # package cache
      - uv_data:/root/.cache/uv
    labels:
      caddy: http://py.fbi.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
    restart: unless-stopped

  ts:
    profiles: ["all", "node"]
    image: ghcr.io/chris-garrett/node:latest
    command: |
      dockerize
        -wait tcp://o2:5080
        bash -c -l '
          yarn run up
        '
    ports:
      - 8032:5173
    environment:
      - O2_TOKEN=ZG9ja2VyQGZiaS5jb206VTdGZmttQjFaY2dHb2FuOA==
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./ts:/work/app
    labels:
      caddy: http://ts.fbi.com
      caddy.reverse_proxy: "{{upstreams 5173}}"
    restart: unless-stopped

  o2:
    profiles: ["all", "o2"]
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment: # https://openobserve.ai/docs/environment-variables/
      ZO_ROOT_USER_EMAIL: docker@fbi.com
      ZO_ROOT_USER_PASSWORD: U7FfkmB1ZcgGoan8
      RUST_LOG: warn
    ports:
      - "8095:5080" # http
      - "8096:5081" # grpc
    volumes:
      - o2_data:/data
    labels:
      caddy_0: http://o2.fbi.com
      caddy_0.reverse_proxy: "{{upstreams 5080}}"
    restart: unless-stopped

volumes:
  caddy_data: {}
  o2_data: {}
  uv_data: {}
